### PR TITLE
Allow setting configs as a parameter

### PR DESCRIPTION
**Pull request by toooni**
Relying only on an ini file could lead to problems in some environments.

### CODE REVIEW

**Comment by david-fiaty-cko** [comment]
@toooni , thank you for the suggestion. We have SDKs in multiple languages (.NET, Python, Go...) and the design tries to maintain consistency across packages.

Adding this possibility would be moving away from the internal design guidelines. We will discuss this and add further comments but it doesn't seem like a direction we would be taking.

Also, could you please explain further in what kind of environment a .ini file could be a problem?

**Comment by toooni** [comment]
Hi @david-fiaty-cko 
If you want to deploy applications to multiple environments (dev, staging, prod) with different configurations, it'll get complicated. It also seems like we can't modify the config path. So we are required to have a config file inside a vendor. Vendors are not copied and modified nowadays. Vendors are installed by composer and locked in a specific version. TBH, the config strategy is currently unusable for modern PHP Applications. The same goes for the logging part of the sdk. PHP has with the PSR-3 (https://www.php-fig.org/psr/psr-3/) a de facto standard how to handle logging.

To clarify: I am not able to disable logging (which by default writes in the web/ directory (symfony) which is public) without being able to change the config outside of the vendor. So this change is a must (could be implemented differently for sure).

I understand that you are trying to minimize maintenance for your packages by keeping everything as consistent between your packages. But this package right now isn't suitable for a modern Symfony/Laravel Application.


> https://github.com/checkout/checkout-sdk-net/wiki/.NET-Core

 Can also be configured without a config file. It also uses a library for logging (LibLog)

Thy python package can be configured by env vars as well (No config file needed).

**Comment by david-fiaty-cko** [comment]
Hi @toooni,
Thank you for the explanations about your context.
We won't be able to modify the constructor as you requested in the PR to add a 4th optional configuration array parameter.

However, I understand your constraints and we could add a public method allowing you to assign your own configuration array. The only difference is that you won't assign this array directly in the constructor, but only after initialisation, using a setter.
Please let me know if this would suit your use case so that we can implement this approach.

Side note, it is currently possible to specify a custom logging path in the config.ini file.
It is also possible to turn off the logging in the same file.

**Comment by toooni** [comment]
Thanks, this will work for us.

I saw that it‘s possible to disable logging in the ini file. The problem there is that the ini file by is placed inside the vendor and can‘t be moves anywhere else. The vendor directory can‘t be modified when using composer (It is with something like this https://github.com/cweagans/composer-patches , which is not really a desirable solution). This makes the ini file (including logging) unusable for every project using composer (which will probably be all of your customers using PHP).

If you want a solution which is at least secure. I‘d disable logging in the the PHP sdk by default. Not everyone using symfony will immediately see that logs are being written in a public accessible folder.

**Comment by toooni** [comment]
@david-fiaty-cko How and when are you going to implement this config setter? I'd like to create a PR, but since the logging settings are set by a call in the constructor I don't see how you want to implement this?

**Comment by aquila-freitas-cko** [comment]
HI @toooni , the PR #8 has been merged to master. Instead of passing an array with the configurations as a parameter, you can now pass the location of the custom configuration file. We cannot completely remove the current config.ini as it's being used already by developers.

The custom configuration should keep the structure of the one in source.

`
$checkout = new CheckoutApi('secret_key', true, 'public_key', '/path/to/config.ini');
`

**Comment by toooni** [comment]
Hi @david-fiaty-cko thanks for the update.
Now we'd be able to make the package run in some way. I still do not understand the way you are forcing people to use the package. This is not at all how things are done today. The default config is not usable for a composer project.

I will maintain a simple fork of this package to avoid an ini file.

**Comment by david-fiaty-cko** [comment]
@toooni I am not sure if there are still blocking points for you as you now have the ability to specify a path to your own configuration file on the server. Could you please confirm?

**Comment by toooni** [comment]
I agree that we now have the ability to use the package in our environment. But I made a package (https://github.com/invit/PayumCheckoutcom) which is a provider of one of the most used php payment libraries (https://github.com/Payum/Payum). I can't specify an ini file inside the repository because of the same reasons you shouldn't do this: I won't be able to predict the location of the ini file in every env and disable logging by default (which is a must since it logs to a public dir by default).

**Comment by david-fiaty-cko** [comment]
@toooni, there is a new release with logging disabled by default.
The suggestions about the .ini file will be considered closely. I hope we have been able to satisfy your requests. Thanks a lot for your comments.

**Comment by toooni** [comment]
@david-fiaty-cko Thank you for disabling logging by default.

Can you please update the package in packagist? The best would be to create a hook: https://packagist.org/about#how-to-update-packages

**Comment by david-fiaty-cko** [comment]
@toooni, packagist is up to date. Please let us know any other issue.

**Comment by david-fiaty-cko** [comment]
@toooni, the SDK has been updated to accept a config  array in the constructor instead of a .ini. file.
Example:

```
$myConfig = array('your config here'); 
$checkoutApi = new CheckoutApi(
            'secret_key',
            'sandbox true or false',
            'public_key',
            $myConfig
        );
```

The 4th parameter now accepts both a file or an array.

**Pull request closed without merging**
