### PR TITLE
Following PSR-1: Class names MUST be declared in StudlyCaps

### PR DESCRIPTION
**Pull request by mtawil**

### CODE REVIEW

**Comment by aquila-freitas-cko** [comment]
Hi @mtawil ,
You didn't actually change any class name. All classes are already in Studly Caps as far as I remember, any specific reason why only `Tests` subnamespace needs to be renamed to lowercase?

Thanks,

**Comment by mtawil** [comment]
Hi @aquila-freitas-cko,

No, not all classes are in StudlyCaps, the test classes in this repo are in lowercase, and I changed it to be in StudlyCaps.

Please check the [file changes](https://github.com/checkout/checkout-sdk-php/pull/46/files).

**Comment by mtawil** [comment]
BTW, there are plenty of standard recommendations that are not followed; if you wish, I can work on it and create a new WIP pull-request.

**Comment by mtawil** [comment]
BTW, there are plenty of PSR that are not followed; if you wish, I can work on it and make a new WIP pull-request.

**Comment by aquila-freitas-cko** [comment]
Sure, we will appreciate your pull requests. Could you run `phpcs --standard=PSR1` in your local machine and see what files are not following PSR-1. In your PR only `Tests` subnamespace needs to be renamed to lowercase.

**Pull request closed without merging**
